/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.android.textfieldboxes;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

@Kroll.module(name="Textfieldboxes", id="ti.android.textfieldboxes")
public class TextfieldboxesModule extends KrollModule
{
	// Standard Debugging variables
	private static final String LCAT = "TextfieldboxesModule";
	private static final boolean DBG = TiConfig.LOGD;
	private static final String ModuleName = "Textfieldboxes";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	@Kroll.constant
    public static final int LIGHT_THEME = 1;
	
	@Kroll.constant
    public static final int DARK_THEME = 2;
	
	@Kroll.constant
    public static final String END_ICON_CLICK = "end_icon_click";
	
	@Kroll.constant
    public static final String ICON_IMAGE_CLICK = "icon_image_click";
	
	@Kroll.constant
    public static final String ON_TEXT_CHANGE = "on_text_change";

	public TextfieldboxesModule()
	{
		super();
	}
	
	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}
}

